/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormUser.java
 *
 * Created on 17 Mei 11, 0:42:55
 */

package org.latihan.ui;

import java.util.List;
import javax.swing.table.AbstractTableModel;
import org.latihan.HbSpring;
import org.latihan.model.UserTab;

/**
 *
 * @author gel
 */
public class FormUser extends javax.swing.JInternalFrame {

    /** Creates new form FormUser */
    private List<UserTab> userTabs;
    private UserTab usertab;
    public FormUser() {
        initComponents();
        jTable1.setAutoCreateColumnsFromModel(false);
        refreshTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tUser = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tblSave = new javax.swing.JButton();
        tblDelete = new javax.swing.JButton();
        tblCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Form User");
        setDoubleBuffered(true);

        tUser.setName("tUser"); // NOI18N

        tNama.setName("tNama"); // NOI18N

        tPass.setName("tPass"); // NOI18N

        jLabel1.setText("User Name");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Password");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Nama");
        jLabel3.setName("jLabel3"); // NOI18N

        tblSave.setText("Save");
        tblSave.setName("tblSave"); // NOI18N
        tblSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSaveActionPerformed(evt);
            }
        });

        tblDelete.setText("Delete");
        tblDelete.setName("tblDelete"); // NOI18N
        tblDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblDeleteActionPerformed(evt);
            }
        });

        tblCancel.setText("Cancel");
        tblCancel.setName("tblCancel"); // NOI18N
        tblCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCancelActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "User Name", "Password", "Nama"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(tblSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tblDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tblCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tUser, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(tNama)
                            .addComponent(tPass)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblSave)
                    .addComponent(tblDelete)
                    .addComponent(tblCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSaveActionPerformed
        // TODO add your handling code here:
        UserTab u = new UserTab();
        u.setUsername(tUser.getText());
        u.setPassword(tPass.getText());
        u.setNama(tNama.getText());
        HbSpring.getSecurityService().saveUserTab(u);
        refreshTable();
        refreshText();
    }//GEN-LAST:event_tblSaveActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()>=0){
        usertab = userTabs .get(jTable1.getSelectedRow());
        tUser.setText(usertab.getUsername());
        tNama.setText(usertab.getNama());
        tPass.setText(usertab.getPassword());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void tblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblDeleteActionPerformed
        // TODO add your handling code here:
        HbSpring.getSecurityService().deleteUserTab(usertab);
        refreshTable();
        refreshText();
    }//GEN-LAST:event_tblDeleteActionPerformed

    private void tblCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCancelActionPerformed
        // TODO add your handling code here:
        refreshText();
    }//GEN-LAST:event_tblCancelActionPerformed

    private void refreshTable(){
    userTabs = HbSpring.getSecurityService().getUserTab();
    jTable1.setModel(new UserTabelModel(userTabs));
    }

    private void refreshText(){
    tUser.setText("");
    tNama.setText("");
    tPass.setText("");
    }

    private class UserTabelModel extends AbstractTableModel{
        private List<UserTab> userTabs;

        public UserTabelModel(List<UserTab> userTabs) {
            this.userTabs = userTabs;
        }


        public int getRowCount() {
            return userTabs.size();
        }

        public int getColumnCount() {
            return 3;
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            UserTab u = userTabs.get(rowIndex);
            if (columnIndex==0){
                return u.getUsername();
            }
            else if(columnIndex == 1){
            return  u.getPassword();
            }
            else if(columnIndex ==2){
            return u.getNama();
            }
            return "";
        }


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tPass;
    private javax.swing.JTextField tUser;
    private javax.swing.JButton tblCancel;
    private javax.swing.JButton tblDelete;
    private javax.swing.JButton tblSave;
    // End of variables declaration//GEN-END:variables

}
